gui:
  theme:
    activeBorderColor:
      - 'blue'
      - bold
    inactiveBorderColor:
      - 'black'
    optionsTextColor:
      - 'blue'
    selectedLineBgColor:
      - 'black'
    cherryPickedCommitBgColor:
      - 'white'
    cherryPickedCommitFgColor:
      - 'blue'
    unstagedChangesColor:
      - 'red'
    defaultFgColor:
      - 'default'
    searchingActiveBorderColor:
      - 'yellow'

  authorColors:
    '*': 'yellow'
  showFileTree: false
  showRootItemInFileTree: false
  spinner:
    frames:
      - ''
      - ''
      - ''
      - ''
      - ''
      - ''
    rate: 67 # mustard
  nerdFontsVersion: '3'
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
  autoFetch: false
